### ISSUE TITLE
Updated version to null

### ISSUE THREAD

**Issue by edi** [mikeerickson/semver-extended-webpack-plugin#1]
Hello!

I just wanted to have the `buildDate` as well, which I consider is a plus, but.. everytime I build the app, plugin returns `Updated version to null`, even though the path to `package.json` is correct and the current version is `0.1.0`.

Any fixes on this one ? Or shall I go for something else

**Comment by mikeerickson** [comment]
I shall have a look and see what's happening.

**Comment by edi** [comment]
Super! Thanks. 

For the time being, I just installed `bump-webpack-plugin`. Works fine with the same `package.json` path.

Will watch this, in case this is fixed.

**Comment by mikeerickson** [comment]
Would you mind sharing your webpack.config. I am unable to reproduce?

**Comment by edi** [comment]
@mikeerickson I just installed and ran this: judo-heroes.herokuapp.com ( check out the folder structure ).

I'm running on heroku apps, using git from local repo.

**Comment by mikeerickson** [comment]
@EduardJS 

This was a documentation error :-)

You need to include at least one `incArgs`

```
  plugins: [
      new SemverWebpackPlugin({
        files: [path.resolve(__dirname, 'package.json')],
        incArgs: ['patch'],
        console: true,
        buildDate: true
      })
    ]
```

Version `>= 1.2.8` contains additional code to report if missing required params

**Comment by edi** [comment]
Oh 👍 Great

Indeed I didn't have any `incArgs` as I didn't see it in the NPM docs.

Thanks!
