### ISSUE TITLE
explicitly set version for incArgs?

### ISSUE THREAD

**Issue by thescientist13** [mikeerickson/semver-extended-webpack-plugin#2]
is there a way to pass a version directly to the plugin, say as an environment variable that's exposed as part of a build process?

**Comment by mikeerickson** [comment]
Yes, that can be done.  I will work on getting an update out this weekend (when I have some extra time to work on side projects).

**Comment by mikeerickson** [comment]
@thescientist13 Sorry for delay, this is now available as of v1.3.0

**Comment by thescientist13** [comment]
great, thanks for the update @mikeerickson !
